[package]
name = "wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
rqrr = "0.4.0"
image = "0.23.14"
wasm-bindgen = "0.2.47"
cargo-debug = "0.3.0"
base64 = "0.13.0"